### ISSUE TITLE
Hi_UCD

### ISSUE THREAD

**Issue by xbysq** [Daisy-7/Hi-UCD-S#1]
Hello, I have read the paper "Large-scale deep learning based binary and semantic change detection in
ultra high resolution remote sensing imagery: From benchmark datasets to
urban application", but I can't find the download link of Hi_UCD. Is there a corresponding download entrance?

**Comment by Daisy-7** [comment]
Hello, the Hi-UCD dataset is being prepared for publication, and relevant information will be published here as soon as possible.

**Comment by Daisy-7** [comment]
We have released Hi-UCD mini dataset. You can download it through google drive link.

**Comment by xbysq** [comment]
> We have released Hi-UCD mini dataset. You can download it through google drive link.

I acquire it, thanks for sharing.
