### ISSUE TITLE
Hi-UCD dataset release date

### ISSUE THREAD

**Issue by jisooshin** [Daisy-7/Hi-UCD-S#11]
Hello,

I am interested in studying Semantic Change Detection using the Hi-UCD dataset.

I was wondering when you plan to release the full Hi-UCD dataset, as currently only the Hi-UCD mini version seems to be available. Any information on this would be greatly appreciated!

Thank you.

**Comment by Daisy-7** [comment]
We have recently released the Hi-UCD dataset. Please see the readme file for details.
