### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by vdakov** [Daisy-7/Hi-UCD-S#16]
Hello, 

I have today requested an access to the Hi-UCD dataset. I intend to use it for my research at TU Delft on fusion modules in urban change detection. Everything wiil be cited as requested. 

Could you tell me what I need to do to get approve, and if nothing, to do so? 

Thank you,
Vasil Dakov

**Comment by Daisy-7** [comment]
I just approved your application. Thank you for your interest in our work.
