### ISSUE TITLE
Regarding hiucd-mini dataset

### ISSUE THREAD

**Issue by keybumbum** [Daisy-7/Hi-UCD-S#23]
Thank you for sharing the datasets! 

While processing the HIUCD-Mini dataset, I noticed a discrepancy in the training folder: there are 250 images, but 294 merged masks. Additionally, the image and mask filenames do not always match. For instance, the image folder contains a file named "583538_53.png," but there is no corresponding mask file with this name in the merged mask folder.

Maybe I download the wrong dataset? or other problems? I really appreciate it If you could check your released hiucd-mini dataset.

**Comment by Daisy-7** [comment]
Hi, I checked the released hiucd-mini dataset. The "583538_53.png" is located in both the images and masks folders. You may have downloaded only part of the dataset, please download it again.

**Comment by keybumbum** [comment]
Thanks for your kind reply and support!
