### ISSUE TITLE
About HIUCD-mini dataset

### ISSUE THREAD

**Issue by YuhangZh** [Daisy-7/Hi-UCD-S#24]
Hi, I am very interested in your work. While working with this dataset, I noticed that only two temporal phases are provided, whereas the introduction mentions three phases: 2017, 2018, and 2019. Is it possible that I did not download the complete dataset? I would greatly appreciate any clarification you can provide. Thank you!

**Comment by Daisy-7** [comment]
Hello, we filtered out the images that have not changed, so some images in this dataset may contain three phases, but we did not select these images and still divided them according to two phases. For the specific data set division, please refer to our paper, thank you!
