### ISSUE TITLE
请问一下您提供的HI-UCD数据集中的mask图片是黑色的，为什么没有提供T1和T2的语义图像，运行不了？

### ISSUE THREAD

**Issue by mrxmxm** [Daisy-7/Hi-UCD-S#26]
![image](https://github.com/user-attachments/assets/96f360db-69cc-4212-9ed5-4f0fcc09cbfe)
就是这种语义图像
![image](https://github.com/user-attachments/assets/b2f80542-4e12-45de-a309-b81e6f6f0396)
这些都没有

**Comment by Daisy-7** [comment]
mask图片包含三个通道，分别为T1、T2语义及其变化信息
