### ISSUE TITLE
Dataset access 

### ISSUE THREAD

**Issue by Essha123** [Daisy-7/Hi-UCD-S#9]
Hello,
Recently, I requested to access your open source dataset. Can you please accept it. 
Looking forward to using your dataset.

Thank you

**Comment by Essha123** [comment]
Thank you for providing the access. I have a question regarding the data. In the provided datasets in folders related to validation and test dataset, the number of images and number of labels are different. For examples in validation folder the images in T1 are 49 but the labels are 49. Can you please let me know why is that?
Thank you

**Comment by Daisy-7** [comment]
Please read the file named _readme.txt_ in the dataset. The number of label files and image files are equal. There are three channels in the label file, representing t1 semantic label, t2 semantic label and change label respectively.
